### ISSUE TITLE
Adding working examples of handling low scores (e.g. adding a recaptcha V2 quiz)

### ISSUE THREAD

**Issue by Nirzaree** [sarthi2395/shinygCAPTCHAv3#2]
Hello, I am working on a shiny application and would be requiring recaptcha in that. Thanks for putting up this repo as I was atleast able to get the basic setup up. However I would also like to add actions on lower scores :  adding a recaptcha v2 quiz in that case would be ideal, then relooking at the new response and taking actions.  
Would it be possible for you to add maybe a working example of such a case? Or some outline for implementing something like this? 
Also I was not able to figure out how to attach this to a submit button on the form. Append new data to the database only if recaptcha is successful. It will help if you could put an example for that too. 

Thanks.

**Comment by sarthi2395** [comment]
I would be happy to help, but I am afraid you might have to ask it in a QnA forum like SO as this is not an issue in the package as such. I will try to create an example and post it on Gist sometime soon, for now I am closing this issue.
